title: "Amanda Aird"
description: "PhD Student in Information Science at CU Boulder"
theme: minima

# Optional links to appear in the footer

email: amanda.aird@colorado.edu
linkedin: linkedin.com/in/amanda-aird/

# Custom navigation labels
nav:
  - title: "About Me"
    url: /
  - title: "Publications"
    url: /publications/
  - title: "CV"
    url: /cv/
