title: "Amanda Aird"
author: "Amanda Aird"
description: "PhD Student in Information Science at CU Boulder"
theme: minima

# Optional links to appear in the footer
social_links:
  email: amanda.aird@colorado.edu
  linkedin: linkedin.com/in/amanda-aird/

header_pages:
  - index.html
  - publications.md
  - cv.md
  
